#!/usr/bin/env bash
set -euo pipefail

source ./code/prelude

recv=$1
selector=$2

echo "bind $recv $selector" > /dev/tty
if [[ $selector == "lookup" ]] && [[ $(basename $recv) == "vtable-vt" ]]; then
  echo " -> lookup (vtable)" > /dev/tty
  $N_CODE_PATH/vtable.lookup $recv $selector
else
  echo " -> send" > /dev/tty
  $N_CODE_PATH/send $N_BASE_PATH/vtable lookup $selector
fi
