#!/usr/bin/env bash
set -euo pipefail

recv=$1
selector=$2

if [[ $selector == "lookup" ]] && [[ ${recv##*/} == "vtable-vt" ]]; then
  ./code/vtable.lookup $recv $selector
else
  ./code/send $recv/vtable lookup $selector
fi
