#!/usr/bin/env bash
set -euo pipefail

recv=$1
echo "send" > /dev/tty
echo "-> test receiver $recv" > /dev/tty
if [[ -L $recv ]]; then
  echo " -> Receiver is link for $recv" > /dev/tty
  recv=$(readlink -n $recv)
  echo " -> Receiver resolved to $recv" > /dev/tty
else
  echo " -> Not a link" > /dev/tty
fi

selector=$2

shift
shift

path_to_impl=$(./code/bind $recv $selector)
echo " -> impl: $path_to_impl" > /dev/tty
$path_to_impl $recv "$@"
